apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: docker-frontend-backend-db 
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:      
      type: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: docker-frontend-backend-db
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: suhailkhan21/feku
          ports:
            - containerPort: 3000
